require 'hammer_cli_foreman/command_extensions/fields'
require 'hammer_cli_foreman/command_extensions/puppet_environment'
require 'hammer_cli_foreman/command_extensions/puppet_environments'
require 'hammer_cli_foreman/command_extensions/option_sources'
require 'hammer_cli_foreman/command_extensions/hosts'
require 'hammer_cli_foreman/command_extensions/ping'
require 'hammer_cli_foreman/command_extensions/status'
