require 'hammer_cli_foreman/command_extensions/fields'
require 'hammer_cli_foreman/command_extensions/puppet_environment'
require 'hammer_cli_foreman/command_extensions/puppet_environments'
require 'hammer_cli_foreman/command_extensions/option_sources'
