require 'hammer_cli_foreman/option_sources/id_params'
require 'hammer_cli_foreman/option_sources/ids_params'
require 'hammer_cli_foreman/option_sources/self_param'
require 'hammer_cli_foreman/option_sources/user_params'
require 'hammer_cli_foreman/option_sources/fields_params'
require 'hammer_cli_foreman/option_sources/puppet_environment_params'
require 'hammer_cli_foreman/option_sources/new_params'
require 'hammer_cli_foreman/option_sources/referenced_resource_id_params'
