require 'hammer_cli_foreman/compute_resources/default/compute_attributes'
require 'hammer_cli_foreman/compute_resources/ec2'
require 'hammer_cli_foreman/compute_resources/gce'
require 'hammer_cli_foreman/compute_resources/libvirt'
require 'hammer_cli_foreman/compute_resources/openstack'
require 'hammer_cli_foreman/compute_resources/ovirt'
require 'hammer_cli_foreman/compute_resources/rackspace'
require 'hammer_cli_foreman/compute_resources/vmware'
